version: "3.8"
services:
  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7.0
    container_name: redis
    restart: always
    command: ["sh", "-c", "redis-server --protected-mode no"]
    ports:
      - "7001:6379"
    volumes:
      - redis_master_data:/data

  redis-slave_1:
    image: redis:7.0
    container_name: redis-slave_1
    restart: always
    command: ["sh", "-c", "redis-server --protected-mode no --slaveof redis 6379"]
    ports:
      - "7002:6379"
    depends_on:
      - redis
    volumes:
      - redis_slave_1_data:/data

  redis-slave_2:
    image: redis:7.0
    container_name: redis-slave_2
    restart: always
    command: ["sh", "-c", "redis-server --protected-mode no --slaveof redis 6379"]
    ports:
      - "7003:6379"
    depends_on:
      - redis
    volumes:
      - redis_slave_2_data:/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  discoverserver:
    build:
      context: ./discoverserver
    container_name: discoverserver
    ports:
      - "8761:8761"

  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discoverserver:8761/eureka
    depends_on:
      - discoverserver

  question-bank-service:
    build:
      context: ./question-bank-service
    container_name: question-bank-service
    ports:
      - "9001:9001"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/jlpt
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discoverserver:8761/eureka
    depends_on:
      - mongodb
      - rabbitmq
      - discoverserver

  exam-service:
    build:
      context: ./exam-service
    container_name: exam-service
    ports:
      - "9002:9002"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/jlpt
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discoverserver:8761/eureka
    depends_on:
      - mongodb
      - redis
      - rabbitmq
      - discoverserver

  scoring-service:
    build:
      context: ./scoring-service
    container_name: scoring-service
    ports:
      - "9003:9003"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/jlpt
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discoverserver:8761/eureka
    depends_on:
      - rabbitmq
      - discoverserver

  authen-service:
    build:
      context: ./authen-service
    container_name: authen-service
    ports:
      - "9004:9004"
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discoverserver:8761/eureka
    depends_on:
      - discoverserver

volumes:
  mongo_data:
  redis_master_data:
  redis_slave_1_data:
  redis_slave_2_data: