spring.application.name=authen-service
server.port= 9004
eureka.client.service-url.defaultZone = http://discoverserver:8761/eureka
eureka.instance.prefer-ip-address=true

jwt.secret= bXktc3VwZXItc2VjcmV0LWtleS1mb3Itant0LTEyMzQ1Ng==
logging.level.org.springframework=INFO
logging.level.com.jlptpracticetest=DEBUG