spring.application.name=question-bank-service
server.port= 9001
eureka.client.service-url.defaultZone = http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true
spring.data.mongodb.uri=mongodb://localhost:27017/jlpt
spring.data.mongodb.auto-index-creation=true