spring.application.name=question-bank-service
server.port= 9001
eureka.client.service-url.defaultZone = http://discoverserver:8761/eureka
eureka.instance.prefer-ip-address=true
spring.data.mongodb.uri=mongodb://localhost:27017/jlpt
spring.data.mongodb.auto-index-creation=true

spring.rabbitmq.template.default-receive-queue=scoring_queue

jwt.secret= bXktc3VwZXItc2VjcmV0LWtleS1mb3Itant0LTEyMzQ1Ng==
logging.level.org.springframework=INFO
logging.level.com.jlptpracticetest=DEBUG